[input]
entrypoint = 0x80000400
elf_path = "../.mp1-build/marioparty/build/marioparty.elf"
rom_file_path = "../.mp1-build/marioparty/baserom.us.z64"
output_func_path = "generated"
relocatable_sections_path = "mp1.us.overlays.txt"
functions_per_output_file = 50

[patches]
stubs = ["__LeoBootGame2"]
ignored = []
